### PR TITLE
Allow frameshift adaptors in constructs

### PR DESCRIPTION
**Pull request by pontushojer**
Fix for issue #74.

### CODE REVIEW

**Comment by FrickTobias** [comment]
I'm not sure we should add the length requirement. My thought is that requiring ~65 (25+40) bases of construct with a max 20 % error rate should suffice in terms of stringency.

Otherwise it looks great though :)

**Comment by marcelm** [comment]
If you don’t add `min_overlap=26`, then you can get partial matches of the 3' end of the adapter to the 5' end of the read. Because the default is to require an overlap of three bases, simply finding `TGG` in the beginning of a read would be enough for a match.

**Comment by FrickTobias** [comment]
Okay, so that is essentially the minimum of matches needed in order to proceed to the alignment-error calculation or am I mistaken? If so, what are the initial requirement of the alignemnt?

**Comment by marcelm** [comment]
The minimum overlap is the minimum number of bases of the adapter that need to be covered by the alignment. These don’t have to be matches necessarily. I don’t know what you mean by initial requirements.

**Comment by FrickTobias** [comment]
Alright. So essentially `min_overlap=26` with `-e 0.2` means we can have an alignment of 26 bases of 26 bases where 5 bases can be inserted or substituted but none can be deleted? 

My thought a deletion would cause the alignment length to be less than 26? Or possibly mistakenly trimming a base from the the next part of the read constructs to increase the length to 26 (if it can be tolerated within the 20% error rate).

I don't know if I'm missing something but currently requiring a minimum length equal to the total length of the construct seem quite stringent. 

PS. Never mind my question about initial requirement, didn't think properly.

**Comment by marcelm** [comment]
> So essentially min_overlap=26 with -e 0.2 means we can have an alignment of 26 bases of 26 bases where 5 bases can be inserted or substituted but none can be deleted?

You can have in total 5 errors, and any of them can be substitutions, insertions or deletions.

The overlap length is computed as the number of adapter bases involved in the alignment. It is not the length of the alignment, precisely because of the issue you mentioned: I don’t want the length to change just because there is an insertion or deletion.

So assume you have the 5' adapter `ANICEADAPTER`. Here is the alignment to a read with a deletion:
```
ANICEADAPTER (adapter)
     ==X====
     AD-PTERANDTHENTHEREST (read)
```
And to a read with an insertion:
```
ANICEADA-PTER (adapter)
     ===X===
     ADARPTERANDTHENTHEREST (read)
```
In both cases, the overlap length is 7. If the error rate allows 1/7 errors (ca 15%), then both alignments will be found.

> I don't know if I'm missing something but currently requiring a minimum length equal to the total length of the construct seem quite stringent.

Use the overlap length to describe what you would expect to see in the read if there were no sequencing errors. If the adapter sequence could be degraded at its 5' end due to a step in your library preparation, then you should use a lower value than the actual adapter length to allow this. If you expect the full sequence to be present, then use `min_overlap=26`. The error rate will then take care of any sequencing errors.

**Comment by FrickTobias** [comment]
Okay, sounds great! Thanks for the explanation!

**Pull request merged**
