### PR TITLE
Output stats file from `buildmolecules`

### PR DESCRIPTION
**Pull request by pontushojer**
Now the pipeline output the stats files.

I also made some additional changes to `buildmolecules`:
- Stats files are now TSV files.
- Added column headers to the files.
- Included barcode in `molecules_per_bc.tsv`.
- `write_molecule_stats` is now a function as it was not related to the `Summary` class.

### CODE REVIEW

**Comment by pontushojer** [comment]
Solves #144

**Comment by FrickTobias** [comment]
Looks good! 

Maybe we could also add a header row to the TSV file?

**Comment by pontushojer** [comment]
> Looks good!
> 
> Maybe we could also add a header row to the TSV file?

They both have headers ;). See lines 261-263 in `buildmolecules`. 

```bash
$ head molecule_stats.tsv 
Reads	Length	Barcode	NrMolecules
4	7091	CGCCGGCCTTAGGTAGGTCG	1
6	9395	CAAGGATGGTAGCTACCACG	1
7	4020	GGCCCTAGCAAGTATGGTCG	2
11	7540	GGCCCTAGCAAGTATGGTCG	2
4	4960	GGAGGTCCGACCCGAAGTTA	2
19	38660	GGAGGTCCGACCCGAAGTTA	2
4	2706	GTAAGAAGCGACTGACGTAA	1
4	4956	GGACTGCGTGCGTGAGGAAG	2
7	18758	GGACTGCGTGCGTGAGGAAG	2

$ head molecules_per_bc.tsv 
Barcode	NrMolecules
CGCCGGCCTTAGGTAGGTCG	1
CAAGGATGGTAGCTACCACG	1
GGCCCTAGCAAGTATGGTCG	2
GGAGGTCCGACCCGAAGTTA	2
GTAAGAAGCGACTGACGTAA	1
GGACTGCGTGCGTGAGGAAG	2
CATAGGTACGCGGGACCTTC	1
CATACATCCGAAGAAATTAA	2
TAAATTTCGTCGCTTCTATG	1
```

**Comment by FrickTobias** [comment]
Ah, nevermind! Totally missed that. Then I'm good with this as it is.

**Pull request merged**
