### PR TITLE
Logging

### PR DESCRIPTION
**Pull request by pontushojer**
Fixing issue #31

Added logger to all python scripts and implemented when appropriate.

### CODE REVIEW

**Comment by marcelm** [comment]
Really nice improvement! I’ve added some review comments.

**Comment by marcelm** [comment]
Did you miss my review comments?

**Comment by FrickTobias** [comment]
Yes, unfortunately I did.

Anyhow, we are unable to find your review comments now so we can fix them in post, were they written directly in the ```pontushojer:logging``` branch?

**Comment by marcelm** [comment]
Oh, ok, that explains something ... I saw the review comments right here, but they were actually marked as *pending*, that is, I had to click on "Submit review". I hope you can see the comments now.

**Pull request merged**
