### PR TITLE
Implement streaming of trimmed fastq into `tagfastq`

### PR DESCRIPTION
**Pull request by pontushojer**
Removes intermediate `trimmed.1.fastq.gz` and `trimmed.2.fastq.gz` files.

Related to issue #116

### CODE REVIEW

**Comment by FrickTobias** [comment]
What do you think about naming the files like `trimmed.barcoded` rather than `trimmed_barcoded` in order to be consistent with the current naming convention used for the BAM files?

**Comment by pontushojer** [comment]
> What do you think about naming the files like `trimmed.barcoded` rather than `trimmed_barcoded` in order to be consistent with the current naming convention used for the BAM files?

Sure! That is more consistent

**Comment by pontushojer** [comment]
I thought this was PR #136 so I added the name change to that PR by mistake. But I can rebase this one after the other PR is merged. So **hold of on merging this for now!!**

**Comment by FrickTobias** [comment]
PR #136 is now merged. 

By the way, I think you can rebase it to the branch before merging since git should the first PRs commit hashes as already merged.

**Pull request merged**
