### PR TITLE
Reference test vcf & bugfix

### PR DESCRIPTION
**Pull request by FrickTobias**
I noticed & patched a bug in the snakemake rule for variant calling.

I also took the time to implement a test so we'll notice if this fails in the future.

PS. Why does `reference_variant` argument always override the `test_config.yaml`? 

This fixes a problem for running both pytest and the `bash tests/run.sh` command. `bash tests/run.sh` requires `test_config.yaml` to have `../` before the reference file but the `pytest` function wants to get it without the `../`. In order to also test for the case of not having a reference pytest writes the file that is given as input to `reference_varaints` or it will remove what is written in the template `test_config.yaml` file.

### CODE REVIEW

**Comment by FrickTobias** [comment]
I also tried having no vcf reference as default in the `test_config.yaml` but from trying to run the pipeline I noticed I got sporadic md5sum changes in the `.phase` file. 

After closer inspection I noticed the length of the variant indel calling seemed to vary from which the changes where hailing from. I'm not sure why this is, but it's worth to keep in mind that the indel calling from `freebayes` doesn't seem that reliable.

Example from outputs after running

```
blr run reference.vcf
mv reference.vcf reference1.vcf
blr run reference.vcf
```
Difference:
```
diff reference1.vcf reference.vcf 
```
```
226c226
< chr1mini	40122	.	CTTTTTTTTTTTTTCGTCTTTTGA	CTTTTTTTTTTTTCGTCTTTTGA	8.43189	.	AB=0.266667;ABP=10.1038;AC=1;AF=0.5;AN=2;AO=4;CIGAR=1M1D22M;DP=15;DPB=14.9583;DPRA=0;EPP=5.18177;EPPR=3.25157;GTI=0;LEN=1;MEANALT=3;MQM=32.25;MQMR=39.8889;NS=1;NUMALT=1;ODDS=1.78663;PAIRED=1;PAIREDR=1;PAO=0.5;PQA=20.5;PQR=20.5;PRO=0.5;QA=117;QR=347;RO=9;RPL=2;RPP=3.0103;RPPR=3.25157;RPR=2;RUN=1;SAF=3;SAP=5.18177;SAR=1;SRF=2;SRP=9.04217;SRR=7;TYPE=del	GT:DP:AD:RO:QR:AO:QA:GL	0/1:15:9,4:9:347:4:117:-5.4651,0,-24.3602
---
> chr1mini	40122	.	CTTTTTTTTTTTTTCGT	CTTTTTTTTTTTTCGT	42.2029	.	AB=0.3125;ABP=7.89611;AC=1;AF=0.5;AN=2;AO=5;CIGAR=1M1D15M;DP=16;DPB=15.7647;DPRA=0;EPP=6.91895;EPPR=3.25157;GTI=0;LEN=1;MEANALT=3;MQM=34.2;MQMR=39.8889;NS=1;NUMALT=1;ODDS=9.71752;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=158;QR=350;RO=9;RPL=3;RPP=3.44459;RPPR=3.25157;RPR=2;RUN=1;SAF=4;SAP=6.91895;SAR=1;SRF=2;SRP=9.04217;SRR=7;TYPE=del	GT:DP:AD:RO:QR:AO:QA:GL	0/1:16:9,5:9:350:5:158:-9.25073,0,-24.6986
278,279c278
< chr1mini	49893	.	CAAAAAAAAAAAAAAAAAGTTA	CAAAAAAAAAAAAAAAAAAGTTA	22.5815	.	AB=0.363636;ABP=4.78696;AC=1;AF=0.5;AN=2;AO=4;CIGAR=1M1I21M;DP=11;DPB=11.0909;DPRA=0;EPP=5.18177;EPPR=5.18177;GTI=0;LEN=1;MEANALT=3;MQM=42;MQMR=37;NS=1;NUMALT=1;ODDS=5.19403;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=102;QR=140;RO=4;RPL=2;RPP=3.0103;RPPR=3.0103;RPR=2;RUN=1;SAF=3;SAP=5.18177;SAR=1;SRF=3;SRP=5.18177;SRR=1;TYPE=ins	GT:DP:AD:RO:QR:AO:QA:GL	0/1:11:4,4:4:140:4:102:-6.44897,0,-9.40276
< chr1mini	49921	.	T	A	1.69164e-06	.	AB=0;ABP=0;AC=0;AF=0;AN=2;AO=2;CIGAR=1X;DP=11;DPB=11;DPRA=0;EPP=7.35324;EPPR=3.25157;GTI=0;LEN=1;MEANALT=1;MQM=41;MQMR=39.7778;NS=1;NUMALT=1;ODDS=14.7584;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=24;QR=284;RO=9;RPL=2;RPP=7.35324;RPPR=5.18177;RPR=0;RUN=1;SAF=2;SAP=7.35324;SAR=0;SRF=4;SRP=3.25157;SRR=5;TYPE=snp	GT:DP:AD:RO:QR:AO:QA:GL	0/0:11:9,2:9:284:2:24:0,-1.03233,-21.356
---
> chr1mini	49893	.	CAAAAAAAAAAAAAAAAAGTTAGAAAAAT	CAAAAAAAAAAAAAAAAAAGTTAGAAAAAT,AAAAAAAAAAAAAAAAAAGTTAGAAAAAT,CAAAAAAAAAAAAAAAAAGTTAGAAAAAA	1.43472	.	AB=0.3,0.2,0.2;ABP=6.48466,10.8276,10.8276;AC=1,0,0;AF=0.5,0,0;AN=2;AO=3,2,2;CIGAR=1M1I28M,1X28M,28M1X;DP=10;DPB=10.1379;DPRA=0,0,0;EPP=9.52472,3.0103,3.0103;EPPR=7.35324;GTI=0;LEN=1,1,1;MEANALT=4,4,4;MQM=42,41,41;MQMR=33;NS=1;NUMALT=3;ODDS=1.12784;PAIRED=1,1,1;PAIREDR=1;PAO=0.333333,0,0.333333;PQA=13.6667,0,13.6667;PQR=13.6667;PRO=0.333333;QA=61,28,24;QR=67;RO=2;RPL=2,1,1;RPP=3.73412,3.0103,3.0103;RPPR=3.0103;RPR=1,1,1;RUN=1,1,1;SAF=2,0,2;SAP=3.73412,7.35324,7.35324;SAR=1,2,0;SRF=1;SRP=3.0103;SRR=1;TYPE=ins,snp,snp	GT:DP:AD:RO:QR:AO:QA:GL	0/1:10:2,3,2,2:2:67:3,2,2:61,28,24:-2.98057,0,-2.91948,-2.58563,-2.83894,-4.84697,-2.95134,-3.20598,-5.78,-6.16042
296d294
< chr1mini	57734	.	GAAAAAAAAAAAAAAGAAAGAA	GAAAAAAAAAAAAAAAGAAAGAA	1.9842	.	AB=0.285714;ABP=5.80219;AC=1;AF=0.5;AN=2;AO=2;CIGAR=1M1I21M;DP=7;DPB=7.04545;DPRA=0;EPP=3.0103;EPPR=11.6962;GTI=0;LEN=1;MEANALT=2;MQM=33;MQMR=42;NS=1;NUMALT=1;ODDS=0.546212;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=65;QR=160;RO=4;RPL=1;RPP=3.0103;RPPR=3.0103;RPR=1;RUN=1;SAF=2;SAP=7.35324;SAR=0;SRF=2;SRP=3.0103;SRR=2;TYPE=ins	GT:DP:AD:RO:QR:AO:QA:GL	0/1:7:4,2:4:160:2:65:-3.59699,0,-11.9514
309c307
< chr1mini	63911	.	GAAAAAAAAAAAAAAGAAAAGTACAT	GAAAAAAAAAAAAAGAAAAGTACAT	0.0455779	.	AB=0.3125;ABP=7.89611;AC=1;AF=0.5;AN=2;AO=5;CIGAR=1M1D24M;DP=16;DPB=15.9231;DPRA=0;EPP=3.44459;EPPR=5.80219;GTI=0;LEN=1;MEANALT=5;MQM=28.8;MQMR=35.8571;NS=1;NUMALT=1;ODDS=4.55163;PAIRED=1;PAIREDR=1;PAO=0.5;PQA=20.5;PQR=20.5;PRO=0.5;QA=89;QR=265;RO=7;RPL=2;RPP=3.44459;RPPR=5.80219;RPR=3;RUN=1;SAF=0;SAP=13.8677;SAR=5;SRF=2;SRP=5.80219;SRR=5;TYPE=del	GT:DP:AD:RO:QR:AO:QA:GL	0/1:16:7,5:7:265:5:89:-3.25234,0,-15.8348
---
> chr1mini	63911	.	GAAAAAAAAAAAAAAGAAAA	GAAAAAAAAAAAAAGAAAA	14.6173	.	AB=0.333333;ABP=7.35324;AC=1;AF=0.5;AN=2;AO=6;CIGAR=1M1D18M;DP=18;DPB=17.75;DPRA=0;EPP=4.45795;EPPR=3.25157;GTI=0;LEN=1;MEANALT=4;MQM=31;MQMR=35.1111;NS=1;NUMALT=1;ODDS=3.33062;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=130;QR=333;RO=9;RPL=3;RPP=3.0103;RPPR=3.25157;RPR=3;RUN=1;SAF=1;SAP=8.80089;SAR=5;SRF=4;SRP=3.25157;SRR=5;TYPE=del	GT:DP:AD:RO:QR:AO:QA:GL	0/1:18:9,6:9:333:6:130:-6.42578,0,-20.8982
```

**Comment by FrickTobias** [comment]
For some reason after rebasing the commit messages from previous PRs are showing up, not sure why but it is the case for this and my next PR.

**Comment by pontushojer** [comment]
Yeah I also find it a bit strange that `freebayes` does not reproduce results for the same input. Checking if the file is created is probably the best we can do for now. 

One thing that I thought about the new test is if we could confirm that the file generated with input as `None` is in fact a symbolic link. `pathlib` has a `is_symlink()` method that could be used.

**Comment by FrickTobias** [comment]
I'm assuming you mean when there is a reference (`None` gives the case where references are called and then there is no symlink).

You mean something like:
```
if reference_variants:  
    assert path(reference.vcf).is_symlink()
else:
    assert path(reference.vcf).is_file()
```

**Comment by pontushojer** [comment]
> You mean something like:
> 
> ```
> if reference_variants:  
>     assert path(reference.vcf).is_symlink()
> else:
>     assert path(reference.vcf).is_file()
> ```

That would work! 👍

**Comment by pontushojer** [comment]
So this looks quite good now. I am gonna go ahead and merge.

**Pull request merged**
